# Generated by Django 5.2.8 on 2025-11-16 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="menu.menu"
            ),
            preserve_default=False,
        ),
    ]
