# Generated by Django 5.2.8 on 2025-11-16 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_menuitem_menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="title",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="title",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu.menu"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="named_url",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
